// @ts-nocheck
/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 */
const documents = {
    "\n    query MenuQuery {\n      menuItems(where: { location: HEADER }) {\n        nodes {\n          uri\n          target\n          label\n        }\n      }\n    }\n  ": types.MenuQueryDocument,
    "\n  query PageQuery($id: ID!, $preview: Boolean = false) {\n    page(id: $id, idType: DATABASE_ID, asPreview: $preview) {\n      isFrontPage\n      title\n      content\n    }\n    posts(first: 5, where: { orderby: { field: DATE, order: DESC } }) {\n      nodes {\n        id\n        uri\n        excerpt\n        title\n        featuredImage {\n          node {\n            sourceUrl\n          }\n        }\n      }\n    }\n  }\n": types.PageQueryDocument,
    "\n  query PostQuery($id: ID!, $preview: Boolean = false) {\n    post(id: $id, idType: DATABASE_ID, asPreview: $preview) {\n      # content\n      date\n      title\n      author {\n        node {\n          name\n        }\n      }\n      contentBlocks {\n        __typename\n        blockName\n        data\n      }\n    }\n  }\n": types.PostQueryDocument,
    "\n  query AllGames($where: RootQueryToGameConnectionWhereArgs, $first: Int) {\n    games(first: $first, where: $where) {\n      nodes {\n        gameId\n        title\n        slug\n        featuredImage {\n          node {\n            sourceUrl(size: LARGE)\n          }\n        }\n        propertiesGame {\n          gameTitle\n          gameDescription\n          metrics {\n            score\n            metric {\n              nodes {\n                name\n              }\n            }\n          }\n        }\n        platform {\n          nodes {\n            name\n          }\n        }\n        tags {\n          nodes {\n            name\n          }\n        }\n        crossplatform {\n          nodes {\n            taxonomyName\n          }\n        }\n      }\n    }\n  }\n": types.AllGamesDocument,
    "\n  query GameBySlug($slug: ID!) {\n    game(id: $slug, idType: SLUG) {\n      title\n      slug\n      featuredImage {\n        node {\n          sourceUrl(size: LARGE)\n        }\n      }\n      platform {\n        nodes {\n          name\n        }\n      }\n      tags {\n        nodes {\n          name\n        }\n      }\n      crossplatform {\n        nodes {\n          name\n        }\n      }\n      players {\n        nodes {\n          name\n        }\n      }\n      propertiesGame {\n        gameTitle\n        gameDescription\n        verdict\n        playtime\n        releaseDate\n        theBad {\n          badPoint\n        }\n        theGood {\n          goodPoint\n        }\n        metrics {\n          description\n          score\n          metric {\n            nodes {\n              name\n            }\n          }\n        }\n      }\n      seo {\n        title\n        metaDesc\n      }\n    }\n  }\n": types.GameBySlugDocument,
    "\n  query AllMetrics {\n    metrics(where: { hideEmpty: false }, first: 100) {\n      nodes {\n        id\n        name\n        slug\n      }\n    }\n  }\n": types.AllMetricsDocument,
    "\n  query ContentInfo($slug: ID!, $idType: ContentNodeIdTypeEnum!) {\n    contentNode(id: $slug, idType: $idType) {\n      contentTypeName\n      databaseId\n      status\n      uri\n    }\n  }\n": types.ContentInfoDocument,
    "\n  query SeoQuery(\n    $slug: ID!\n    $idType: ContentNodeIdTypeEnum\n    $preview: Boolean = false\n  ) {\n    contentNode(id: $slug, idType: $idType, asPreview: $preview) {\n      seo {\n        canonical\n        cornerstone\n        focuskw\n        metaDesc\n        metaKeywords\n        metaRobotsNofollow\n        metaRobotsNoindex\n        opengraphAuthor\n        opengraphDescription\n        opengraphModifiedTime\n        opengraphPublishedTime\n        opengraphPublisher\n        opengraphSiteName\n        opengraphTitle\n        opengraphType\n        opengraphUrl\n        readingTime\n        title\n        twitterDescription\n        twitterTitle\n        opengraphImage {\n          altText\n          mediaDetails {\n            height\n            width\n          }\n          sourceUrl\n        }\n        twitterImage {\n          altText\n          mediaDetails {\n            width\n            height\n          }\n          sourceUrl\n        }\n      }\n    }\n  }\n": types.SeoQueryDocument,
    "\n  query HomeFeaturedGames {\n    page(id: 8, idType: DATABASE_ID) {\n      id\n      title\n      slug\n      seo {\n        title\n        metaDesc\n      }\n      propertiesHome {\n        featuredTitle\n        featuredMetrics {\n          nodes {\n            name\n          }\n        }\n        selectGames {\n          selectedGame {\n            nodes {\n              ... on Game {\n                id\n                title\n                slug\n                featuredImage {\n                  node {\n                    sourceUrl(size: LARGE)\n                  }\n                }\n                tags {\n                  nodes {\n                    name\n                  }\n                }\n                platform {\n                  nodes {\n                    name\n                  }\n                }\n                propertiesGame {\n                  gameTitle\n                  gameDescription\n                  verdict\n                  playtime\n                  metrics {\n                    description\n                    score\n                    metric {\n                      nodes {\n                        name\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.HomeFeaturedGamesDocument,
    "\n  query AllRankings($first: Int) {\n    rankings(first: $first) {\n      nodes {\n        id\n        title\n        slug\n        featuredImage {\n          node {\n            sourceUrl(size: LARGE)\n          }\n        }\n        propertiesGamePost {\n          description\n          selectGames {\n            selectedGame {\n              nodes {\n                ... on Game {\n                  title\n                  slug\n                  propertiesGame {\n                    metrics {\n                      metric {\n                        nodes {\n                          name\n                        }\n                      }\n                      score\n                    }\n                    playtime\n                  }\n                  platform {\n                    nodes {\n                      name\n                    }\n                  }\n                  featuredImage {\n                    node {\n                      sourceUrl\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n": types.AllRankingsDocument,
    "\n  query RankingBySlug($slug: ID!) {\n    ranking(id: $slug, idType: SLUG) {\n      id\n      title\n      slug\n      featuredImage {\n        node {\n          sourceUrl(size: LARGE)\n        }\n      }\n      propertiesGamePost {\n        description\n        selectGames {\n          selectedGame {\n            nodes {\n              ... on Game {\n                id\n                title\n                slug\n                featuredImage {\n                  node {\n                    sourceUrl(size: LARGE)\n                  }\n                }\n                propertiesGame {\n                  gameTitle\n                  gameDescription\n                  theBad {\n                    badPoint\n                  }\n                  theGood {\n                    goodPoint\n                  }\n                  verdict\n                  metrics {\n                    description\n                    score\n                    metric {\n                      nodes {\n                        name\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      seo {\n        title\n        metaDesc\n      }\n    }\n  }\n": types.RankingBySlugDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n    query MenuQuery {\n      menuItems(where: { location: HEADER }) {\n        nodes {\n          uri\n          target\n          label\n        }\n      }\n    }\n  "): (typeof documents)["\n    query MenuQuery {\n      menuItems(where: { location: HEADER }) {\n        nodes {\n          uri\n          target\n          label\n        }\n      }\n    }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PageQuery($id: ID!, $preview: Boolean = false) {\n    page(id: $id, idType: DATABASE_ID, asPreview: $preview) {\n      isFrontPage\n      title\n      content\n    }\n    posts(first: 5, where: { orderby: { field: DATE, order: DESC } }) {\n      nodes {\n        id\n        uri\n        excerpt\n        title\n        featuredImage {\n          node {\n            sourceUrl\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query PageQuery($id: ID!, $preview: Boolean = false) {\n    page(id: $id, idType: DATABASE_ID, asPreview: $preview) {\n      isFrontPage\n      title\n      content\n    }\n    posts(first: 5, where: { orderby: { field: DATE, order: DESC } }) {\n      nodes {\n        id\n        uri\n        excerpt\n        title\n        featuredImage {\n          node {\n            sourceUrl\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PostQuery($id: ID!, $preview: Boolean = false) {\n    post(id: $id, idType: DATABASE_ID, asPreview: $preview) {\n      # content\n      date\n      title\n      author {\n        node {\n          name\n        }\n      }\n      contentBlocks {\n        __typename\n        blockName\n        data\n      }\n    }\n  }\n"): (typeof documents)["\n  query PostQuery($id: ID!, $preview: Boolean = false) {\n    post(id: $id, idType: DATABASE_ID, asPreview: $preview) {\n      # content\n      date\n      title\n      author {\n        node {\n          name\n        }\n      }\n      contentBlocks {\n        __typename\n        blockName\n        data\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AllGames($where: RootQueryToGameConnectionWhereArgs, $first: Int) {\n    games(first: $first, where: $where) {\n      nodes {\n        gameId\n        title\n        slug\n        featuredImage {\n          node {\n            sourceUrl(size: LARGE)\n          }\n        }\n        propertiesGame {\n          gameTitle\n          gameDescription\n          metrics {\n            score\n            metric {\n              nodes {\n                name\n              }\n            }\n          }\n        }\n        platform {\n          nodes {\n            name\n          }\n        }\n        tags {\n          nodes {\n            name\n          }\n        }\n        crossplatform {\n          nodes {\n            taxonomyName\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query AllGames($where: RootQueryToGameConnectionWhereArgs, $first: Int) {\n    games(first: $first, where: $where) {\n      nodes {\n        gameId\n        title\n        slug\n        featuredImage {\n          node {\n            sourceUrl(size: LARGE)\n          }\n        }\n        propertiesGame {\n          gameTitle\n          gameDescription\n          metrics {\n            score\n            metric {\n              nodes {\n                name\n              }\n            }\n          }\n        }\n        platform {\n          nodes {\n            name\n          }\n        }\n        tags {\n          nodes {\n            name\n          }\n        }\n        crossplatform {\n          nodes {\n            taxonomyName\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GameBySlug($slug: ID!) {\n    game(id: $slug, idType: SLUG) {\n      title\n      slug\n      featuredImage {\n        node {\n          sourceUrl(size: LARGE)\n        }\n      }\n      platform {\n        nodes {\n          name\n        }\n      }\n      tags {\n        nodes {\n          name\n        }\n      }\n      crossplatform {\n        nodes {\n          name\n        }\n      }\n      players {\n        nodes {\n          name\n        }\n      }\n      propertiesGame {\n        gameTitle\n        gameDescription\n        verdict\n        playtime\n        releaseDate\n        theBad {\n          badPoint\n        }\n        theGood {\n          goodPoint\n        }\n        metrics {\n          description\n          score\n          metric {\n            nodes {\n              name\n            }\n          }\n        }\n      }\n      seo {\n        title\n        metaDesc\n      }\n    }\n  }\n"): (typeof documents)["\n  query GameBySlug($slug: ID!) {\n    game(id: $slug, idType: SLUG) {\n      title\n      slug\n      featuredImage {\n        node {\n          sourceUrl(size: LARGE)\n        }\n      }\n      platform {\n        nodes {\n          name\n        }\n      }\n      tags {\n        nodes {\n          name\n        }\n      }\n      crossplatform {\n        nodes {\n          name\n        }\n      }\n      players {\n        nodes {\n          name\n        }\n      }\n      propertiesGame {\n        gameTitle\n        gameDescription\n        verdict\n        playtime\n        releaseDate\n        theBad {\n          badPoint\n        }\n        theGood {\n          goodPoint\n        }\n        metrics {\n          description\n          score\n          metric {\n            nodes {\n              name\n            }\n          }\n        }\n      }\n      seo {\n        title\n        metaDesc\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AllMetrics {\n    metrics(where: { hideEmpty: false }, first: 100) {\n      nodes {\n        id\n        name\n        slug\n      }\n    }\n  }\n"): (typeof documents)["\n  query AllMetrics {\n    metrics(where: { hideEmpty: false }, first: 100) {\n      nodes {\n        id\n        name\n        slug\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ContentInfo($slug: ID!, $idType: ContentNodeIdTypeEnum!) {\n    contentNode(id: $slug, idType: $idType) {\n      contentTypeName\n      databaseId\n      status\n      uri\n    }\n  }\n"): (typeof documents)["\n  query ContentInfo($slug: ID!, $idType: ContentNodeIdTypeEnum!) {\n    contentNode(id: $slug, idType: $idType) {\n      contentTypeName\n      databaseId\n      status\n      uri\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query SeoQuery(\n    $slug: ID!\n    $idType: ContentNodeIdTypeEnum\n    $preview: Boolean = false\n  ) {\n    contentNode(id: $slug, idType: $idType, asPreview: $preview) {\n      seo {\n        canonical\n        cornerstone\n        focuskw\n        metaDesc\n        metaKeywords\n        metaRobotsNofollow\n        metaRobotsNoindex\n        opengraphAuthor\n        opengraphDescription\n        opengraphModifiedTime\n        opengraphPublishedTime\n        opengraphPublisher\n        opengraphSiteName\n        opengraphTitle\n        opengraphType\n        opengraphUrl\n        readingTime\n        title\n        twitterDescription\n        twitterTitle\n        opengraphImage {\n          altText\n          mediaDetails {\n            height\n            width\n          }\n          sourceUrl\n        }\n        twitterImage {\n          altText\n          mediaDetails {\n            width\n            height\n          }\n          sourceUrl\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query SeoQuery(\n    $slug: ID!\n    $idType: ContentNodeIdTypeEnum\n    $preview: Boolean = false\n  ) {\n    contentNode(id: $slug, idType: $idType, asPreview: $preview) {\n      seo {\n        canonical\n        cornerstone\n        focuskw\n        metaDesc\n        metaKeywords\n        metaRobotsNofollow\n        metaRobotsNoindex\n        opengraphAuthor\n        opengraphDescription\n        opengraphModifiedTime\n        opengraphPublishedTime\n        opengraphPublisher\n        opengraphSiteName\n        opengraphTitle\n        opengraphType\n        opengraphUrl\n        readingTime\n        title\n        twitterDescription\n        twitterTitle\n        opengraphImage {\n          altText\n          mediaDetails {\n            height\n            width\n          }\n          sourceUrl\n        }\n        twitterImage {\n          altText\n          mediaDetails {\n            width\n            height\n          }\n          sourceUrl\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query HomeFeaturedGames {\n    page(id: 8, idType: DATABASE_ID) {\n      id\n      title\n      slug\n      seo {\n        title\n        metaDesc\n      }\n      propertiesHome {\n        featuredTitle\n        featuredMetrics {\n          nodes {\n            name\n          }\n        }\n        selectGames {\n          selectedGame {\n            nodes {\n              ... on Game {\n                id\n                title\n                slug\n                featuredImage {\n                  node {\n                    sourceUrl(size: LARGE)\n                  }\n                }\n                tags {\n                  nodes {\n                    name\n                  }\n                }\n                platform {\n                  nodes {\n                    name\n                  }\n                }\n                propertiesGame {\n                  gameTitle\n                  gameDescription\n                  verdict\n                  playtime\n                  metrics {\n                    description\n                    score\n                    metric {\n                      nodes {\n                        name\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query HomeFeaturedGames {\n    page(id: 8, idType: DATABASE_ID) {\n      id\n      title\n      slug\n      seo {\n        title\n        metaDesc\n      }\n      propertiesHome {\n        featuredTitle\n        featuredMetrics {\n          nodes {\n            name\n          }\n        }\n        selectGames {\n          selectedGame {\n            nodes {\n              ... on Game {\n                id\n                title\n                slug\n                featuredImage {\n                  node {\n                    sourceUrl(size: LARGE)\n                  }\n                }\n                tags {\n                  nodes {\n                    name\n                  }\n                }\n                platform {\n                  nodes {\n                    name\n                  }\n                }\n                propertiesGame {\n                  gameTitle\n                  gameDescription\n                  verdict\n                  playtime\n                  metrics {\n                    description\n                    score\n                    metric {\n                      nodes {\n                        name\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AllRankings($first: Int) {\n    rankings(first: $first) {\n      nodes {\n        id\n        title\n        slug\n        featuredImage {\n          node {\n            sourceUrl(size: LARGE)\n          }\n        }\n        propertiesGamePost {\n          description\n          selectGames {\n            selectedGame {\n              nodes {\n                ... on Game {\n                  title\n                  slug\n                  propertiesGame {\n                    metrics {\n                      metric {\n                        nodes {\n                          name\n                        }\n                      }\n                      score\n                    }\n                    playtime\n                  }\n                  platform {\n                    nodes {\n                      name\n                    }\n                  }\n                  featuredImage {\n                    node {\n                      sourceUrl\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query AllRankings($first: Int) {\n    rankings(first: $first) {\n      nodes {\n        id\n        title\n        slug\n        featuredImage {\n          node {\n            sourceUrl(size: LARGE)\n          }\n        }\n        propertiesGamePost {\n          description\n          selectGames {\n            selectedGame {\n              nodes {\n                ... on Game {\n                  title\n                  slug\n                  propertiesGame {\n                    metrics {\n                      metric {\n                        nodes {\n                          name\n                        }\n                      }\n                      score\n                    }\n                    playtime\n                  }\n                  platform {\n                    nodes {\n                      name\n                    }\n                  }\n                  featuredImage {\n                    node {\n                      sourceUrl\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query RankingBySlug($slug: ID!) {\n    ranking(id: $slug, idType: SLUG) {\n      id\n      title\n      slug\n      featuredImage {\n        node {\n          sourceUrl(size: LARGE)\n        }\n      }\n      propertiesGamePost {\n        description\n        selectGames {\n          selectedGame {\n            nodes {\n              ... on Game {\n                id\n                title\n                slug\n                featuredImage {\n                  node {\n                    sourceUrl(size: LARGE)\n                  }\n                }\n                propertiesGame {\n                  gameTitle\n                  gameDescription\n                  theBad {\n                    badPoint\n                  }\n                  theGood {\n                    goodPoint\n                  }\n                  verdict\n                  metrics {\n                    description\n                    score\n                    metric {\n                      nodes {\n                        name\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      seo {\n        title\n        metaDesc\n      }\n    }\n  }\n"): (typeof documents)["\n  query RankingBySlug($slug: ID!) {\n    ranking(id: $slug, idType: SLUG) {\n      id\n      title\n      slug\n      featuredImage {\n        node {\n          sourceUrl(size: LARGE)\n        }\n      }\n      propertiesGamePost {\n        description\n        selectGames {\n          selectedGame {\n            nodes {\n              ... on Game {\n                id\n                title\n                slug\n                featuredImage {\n                  node {\n                    sourceUrl(size: LARGE)\n                  }\n                }\n                propertiesGame {\n                  gameTitle\n                  gameDescription\n                  theBad {\n                    badPoint\n                  }\n                  theGood {\n                    goodPoint\n                  }\n                  verdict\n                  metrics {\n                    description\n                    score\n                    metric {\n                      nodes {\n                        name\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n      seo {\n        title\n        metaDesc\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;